#!/bin/bash
. ./VE_install
. ./VE_enchant
. ./VE_mta
. ./VE_nginx
. ./functions

#add_site example.org;
#nginx -t;
#del_site example.org;

#exit;




case "$1" in
install) install
;;
add) add_site $2
;;
del) del_site $2 
;;
*) my_help
;;
esac



