#!/bin/bash
### repository for php-7

function add_repo_dotdeb {
	title "Adding dotdeb.org repo"; 
	apt-get install -y curl > /dev/null >&1 || error "Curl installation failed.";
	backup_file /etc/apt/sources.list;
	echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list;
	curl https://www.dotdeb.org/dotdeb.gpg -s | apt-key add - > /dev/null 2>&1 || error "Apt error. Check network";
	apt-get update > /dev/null 2>&1 || error "Apt error. Check network";
}

### APT

function apt-auto {
	title "Apt clean & update & upgrade"
	apt-get clean > /dev/null 2>&1; 
	apt-get update > /dev/null 2>&1 || error "Apt error. Check network";
	apt-get upgrade -y > /dev/null 2>&1 || error "System upgrade error. Check manualy.";
}

### Install nginx (5.7 mb)

function install_nginx {
	title "Installig nginx";
	apt-get install -y nginx > /dev/null 2>&1 || error "Nginx installation error";
	mkdir -p /etc/nginx/ssl || error "Can not create /etc/nginx/ssl";
}

### Installing acme.sh

function install_acme {
	title "Installig acme.sh";
	apt-get install -y curl cron netcat openssl > /dev/null 2>&1 || error "Dependences installation error.";
	curl -s https://get.acme.sh | sh > /dev/null 2>&1;
}

### Install MySQL (96.4 mb)

function install_mysql {
	title "Installig MySQL";
	debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password string $1";
	debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password_again string $1";
	apt-get install -y mysql-server mysql-client > /dev/null 2>&1 || error "MySQL installation error";
}
    
### Install php 7 (101 mb)

function install_php_7 	{
	add_repo_dotdeb;
	title "Installig PHP 7";
	apt-get install -y php7.0 php7.0-cli php7.0-fpm php7.0-curl php7.0-gd php7.0-imagick php7.0-mcrypt php7.0-imap php7.0-mbstring php7.0-xml php7.0-xmlrpc php7.0-xsl php7.0-json php7.0-memcached php7.0-apcu php7.0-apcu-bc php7.0-opcache php7.0-mysql php7.0-sqlite3 php7.0-pgsql php7.0-redis php7.0-interbase php7.0-odbc php7.0-zip php7.0-bz2 php7.0-dba php7.0-enchant php7.0-gmp php7.0-igbinary php7.0-intl php7.0-ldap php7.0-msgpack php7.0-geoip php7.0-readline php7.0-recode php7.0-tidy php7.0-sqlite3 > /dev/null 2>&1 || error "PHP 7 installation error";
}

### Install php 5 (123 mb)

function install_php_5 {
	title "Installig PHP 5";
	apt-get install -y php5 php5-cli php5-apcu php5-geoip php5-gnupg php5-imagick php5-json php5-memcache php5-memcached php5-oauth php5-pecl-http php5-redis php5-cgi php5-curl php5-fpm php5-enchant php5-gd php5-imap php5-gmp php5-intl php5-ldap php5-mcrypt php5-mysql php5-odbc php5-pgsql php5-readline php5-tidy php5-xmlrpc php5-sqlite php5-xsl > /dev/null 2>&1 || error "PHP 5 installation error";
}

### Complete install

function install {
	read -p "`question 'Enter passwd for MySQL root user: '`" mysqlpasswd
	apt-auto;
	install_nginx;
	install_acme;
	install_php_5;
	install_php_7;
	install_mysql $mysqlpasswd;
}

