#!/bin/bash
#domain
#mailpasswd
#user
#password
#mysqlrootpasswd

function install_mta {
	domain=$1; mysqlrootpasswd=$2; mailpasswd=$2; echo $domain > /etc/mailname; title "Installing MTA (postfix & dovecot).";
	git clone https://github.com/egeneralov/mta.git > /dev/null 2>&1;
	cd mta;
	openssl req -nodes -newkey rsa:2048 -keyout postfix/server.key -out postfix/server.crt -subj "/C=RU/ST=Name Surname/L=Location/O=Company/OU=Department/CN=$domain" > /dev/null 2>&1;
	apt-get install -y dovecot-core dovecot-imapd dovecot-mysql dovecot-pop3d dovecot-sieve postfix postfix-mysql > /dev/null 2>&1 || error "Installing MTA from apt failed";

	debconf-set-selections <<< "postfix postfix/mailname string $domain";
	debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'";
	/etc/init.d/postfix stop > /dev/null 2>&1; /etc/init.d/dovecot stop > /dev/null 2>&1;
	groupadd -g 5000 vmail > /dev/null 2>&1; useradd -g vmail -u 5000 vmail -d /home/vmail > /dev/null 2>&1;
	mkdir -p /home/vmail/$domain/$user; chown -R vmail:vmail /home/vmail/;
	echo "CREATE DATABASE mail;" | mysql -p$mysqlrootpasswd mysql > /dev/null 2>&1 || error_only "create database failed";
	echo "CREATE USER 'mail'@'localhost' IDENTIFIED BY '$mailpasswd';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "create mail db user failed";
	echo "GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost';" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 ||error_only "mysql set user permissions failed";
	echo "FLUSH PRIVILEGES;" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1 || error_only "flush privileges failed";
	mysql -p$mysqlrootpasswd mail < mail.sql > /dev/null 2>&1 || error_only "import sql file to mail db failed";
	sed -i "s/mynewpassword/$mailpasswd/g" postfix/virtual_* dovecot/dovecot-sql.conf;
	rm -rf /etc/dovecot || error_only "remove /etc/dovecot failed"; rm -rf /etc/postfix || error_only "remove /etc/postfix failed";
	cp -r postfix /etc/ || error_only "replace dovecot config failed"; cp -r dovecot /etc/ || error_only "replace postfix config failed";
	sed -i "s/$mailpasswd/mynewpassword/g" postfix/virtual_* dovecot/dovecot-sql.conf;
	/etc/init.d/postfix start > /dev/null 2>&1 || error_only "postfix start failed"; /etc/init.d/dovecot start > /dev/null 2>&1 || error_only "dovecot start failed";
	cd ..; rm -rf mta;
}

function add_mail_domain { echo "REPLACE INTO `domains` SET `domain` = '$1';" | mysql -p$2 mail; }

function add_mail_user {
	domain=$1;
	email="$2@$domain";
	password=$3;
	mysqlrootpasswd=$4;
	echo "INSERT INTO \`domains\` (\`domain\`) VALUES ('$domain');" | mysql -p$2 mail
	echo "INSERT INTO \`users\` (\`email\`, \`password\`, \`quota\`, \`domain\`) VALUES ('$user@$domain', encrypt('$password'), '20971520', '$domain');" | mysql -p$mysqlrootpasswd mail > /dev/null 2>&1;
}





