#!/bin/bash

#### Simplest nginx config

function nginx-config-simple {
cat <<< "server {
	listen 80;
	root /sites/$1;
	index index.html;
	server_name $1 www.$1;		
}" > /etc/nginx/sites-available/$1
} # nginx-config-simple

#### Simplest nginx config with acme

function nginx-config-acme {
cat <<< "
server {
	listen 80;
	root /sites/$1;
	index index.html;
	server_name $1 www.$1;
	location /.well-known/acme-challenge {
		allow all;
		autoindex on;
	}
}" > /etc/nginx/sites-available/$1

} # nginx-config-acme





### Rewrite

#### www -> http

function nginx-config-rewrite-www-http {
	echo "server { server_name www.$1; listen 80; return 301 http://$1\$request_uri;}" > /etc/nginx/sites-available/$1
}

#### www -> https

function nginx-config-rewrite-www-https {
	echo "server { server_name www.$1; listen 80; return 301 https://$1\$request_uri;}" > /etc/nginx/sites-available/$1
}

#### http -> httpss

function nginx-config-rewrite-http-https {
	echo "server { server_name $1; listen 80; return 301 https://$http_host\$request_uri? permanent;}" > /etc/nginx/sites-available/$1
}

